name: Actions

on: [push]

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: build and deploy
    if: github.ref == 'refs/heads/main'
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
